### ISSUE TITLE
"Unknown property labels" in stack_plot

### ISSUE THREAD

**Issue by shaisachs** [erikbern/git-of-theseus#11]
Great project! I was able to get through the analysis fine, but found this when I tried stack_plot.py cohorts.json:

```
$ python stack_plot.py cohorts.json
Traceback (most recent call last):
  File "stack_plot.py", line 9, in <module>
    labels=data['labels'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 3165, in stackplot
    ret = ax.stackplot(x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 6844, in stackplot
    return mstack.stackplot(self, x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/stackplot.py", line 101, in stackplot
    **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 7059, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 742, in __init__
    Collection.__init__(self, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 128, in __init__
    self.update(kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 739, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property labels
```

That said, `python survival_plot.py survival.json` worked out fine.

**Comment by erikbern** [comment]
that's weird, not sure what's going on. is the kwarg `labels` that it's complaining about? seems like it. maybe you have an old version of matplotlib?

**Comment by erikbern** [comment]
the newest version of matplotlib def works. did you install it in a virtualenv?

**Comment by nicolasff** [comment]
I hit this too with matplotlib 1.3.1. Running `pip install matplotlib --upgrade` installed 1.5.3 and fixed the issue.

**Comment by shaisachs** [comment]
Excellent, thanks so much! That does get me past this issue, though I'm now seeing a problem with `import _thread` inside the dateutil package. Still I think we can close this particular issue.
