### ISSUE TITLE
Can't generate cohort plot

### ISSUE THREAD

**Issue by erasmas** [erikbern/git-of-theseus#19]
I'm getting following error, when I run `python stack_plot.py cohorts.json`.
I was able to successfully generate `cohorts.json` with `python analyze.py <path to repo>`

```
Traceback (most recent call last):
  File "stack_plot.py", line 15, in <module>
    labels=data['labels'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 3165, in stackplot
    ret = ax.stackplot(x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 6844, in stackplot
    return mstack.stackplot(self, x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/stackplot.py", line 101, in stackplot
    **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 7059, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 742, in __init__
    Collection.__init__(self, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 128, in __init__
    self.update(kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 739, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property labels
```

**Comment by erikbern** [comment]
i think you need to upgrade your version of matplotlib. see #11
