### ISSUE TITLE
ImportError: No module named git

### ISSUE THREAD

**Issue by dball** [erikbern/git-of-theseus#3]
I get this after installing the requirements:

```
~/src/git-of-theseus[master]$ python analyze.py ../clojure
Traceback (most recent call last):
  File "analyze.py", line 2, in <module>
    import argparse, git, datetime, numpy, traceback, time, os, fnmatch, json, progressbar
ImportError: No module named git
```

**Comment by erikbern** [comment]
weird, seems to work for me:

```
$ pyvenv-3.5 env
$ env/bin/pip install -r requirements.txt
$ env/bin/python analyze.py .
```

**Comment by dmit** [comment]
Saw the same error with Python 2.7. Worked fine with Python 3.

**Comment by erikbern** [comment]
weird – i just tried python 2.7 and it works fine

```
$ virtualenv env
$ env/bin/pip install -r requirements.txt
$ env/bin/python analyze.py .
```

**Comment by AndreKR** [comment]
I have the same problem, with both python 2.7 and python 3.

Here's a complete log of what I did:

```
docker run -it alpine:latest /bin/sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
v3.5.2-14-gd7ba0e189f [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
v3.5.2-14-gd7ba0e189f [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
OK: 7962 distinct packages available
/ # apk add git python
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 70 MiB in 26 packages
/ # git clone https://github.com/erikbern/git-of-theseus
Cloning into 'git-of-theseus'...
remote: Counting objects: 204, done.
Receiving objects: 100% (204/204), 1.27 MiB | 190.00 KiB/s, done.
remote: Total 204 (delta 0), reused 0 (delta 0), pack-reused 204
Resolving deltas: 100% (82/82), done.
/ # cd git-of-theseus
/git-of-theseus # pip install -r requirements.txt
/bin/sh: pip: not found
/git-of-theseus # apk add py-pip
(2/2) Installing py2-pip (9.0.0-r1)Executing busybox-1.25.1-r0.trigger
OK: 80 MiB in 28 packages#########]
/git-of-theseus # pip install -r requirements.txt
Collecting gitpython (from -r requirements.txt (line 1))
  Downloading GitPython-2.1.3-py2.py3-none-any.whl (442kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 450kB 331kB/s
Collecting numpy (from -r requirements.txt (line 2))
  Downloading numpy-1.12.1.zip (4.8MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 4.8MB 48kB/s
Collecting progressbar2 (from -r requirements.txt (line 3))
  Downloading progressbar2-3.16.0-py2.py3-none-any.whl
Collecting matplotlib (from -r requirements.txt (line 5))
  Downloading matplotlib-2.0.0.tar.gz (53.2MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 53.2MB 14kB/s
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.0.0]
                    python: yes [2.7.13 (default, Dec 22 2016, 09:22:15)  [GCC
                            6.2.1 20160822]]
                  platform: yes [linux2]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
                       six: yes [six was not found.pip will attempt to install
                            it after matplotlib.]
                  dateutil: yes [dateutil was not found. It is required for date
                            axis support. pip/easy_install may attempt to
                            install it after matplotlib.]
               functools32: yes [functools32 was not found. It is required
                            forPython versions prior to 3.2]
              subprocess32: yes [subprocess32 was not found. It used  for Python
                            versions prior to 3.2 to improves functionality on
                            Linux and OSX]
                      pytz: yes [pytz was not found. pip will attempt to install
                            it after matplotlib.]
                    cycler: yes [cycler was not found. pip will attempt to
                            install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4nAIAt/matplotlib/
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/git-of-theseus # cd ..
/ # git clone https://192.168.1.40/shop.git
Cloning into 'shop'...
remote: Counting objects: 152651, done.
remote: Compressing objects: 100% (43538/43538), done.
remote: Total 152651 (delta 110218), reused 150036 (delta 108445)
Receiving objects: 100% (152651/152651), 633.10 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (110218/110218), done.
/ # cd git-of-theseus/
/git-of-theseus # python analyze.py ../shop/
Traceback (most recent call last):
  File "analyze.py", line 18, in <module>
    import argparse, git, datetime, numpy, traceback, time, os, fnmatch, json, progressbar
ImportError: No module named git
/git-of-theseus # pip install -r requirements.txt
Collecting gitpython (from -r requirements.txt (line 1))
  Using cached GitPython-2.1.3-py2.py3-none-any.whl
Collecting numpy (from -r requirements.txt (line 2))
  Using cached numpy-1.12.1.zip
Collecting progressbar2 (from -r requirements.txt (line 3))
  Using cached progressbar2-3.16.0-py2.py3-none-any.whl
Collecting matplotlib (from -r requirements.txt (line 5))
  Using cached matplotlib-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.0.0]
                    python: yes [2.7.13 (default, Dec 22 2016, 09:22:15)  [GCC
                            6.2.1 20160822]]
                  platform: yes [linux2]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
                       six: yes [six was not found.pip will attempt to install
                            it after matplotlib.]
                  dateutil: yes [dateutil was not found. It is required for date
                            axis support. pip/easy_install may attempt to
                            install it after matplotlib.]
               functools32: yes [functools32 was not found. It is required
                            forPython versions prior to 3.2]
              subprocess32: yes [subprocess32 was not found. It used  for Python
                            versions prior to 3.2 to improves functionality on
                            Linux and OSX]
                      pytz: yes [pytz was not found. pip will attempt to install
                            it after matplotlib.]
                    cycler: yes [cycler was not found. pip will attempt to
                            install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Pb4fGY/matplotlib/
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/git-of-theseus # apk del python
OK: 80 MiB in 28 packages
/git-of-theseus # apk del py-pip
Executing busybox-1.25.1-r0.trigger
OK: 23 MiB in 17 packages
/git-of-theseus # apk add python3
Executing busybox-1.25.1-r0.trigger
OK: 90 MiB in 27 packages
/git-of-theseus # apk add py-pip
Executing busybox-1.25.1-r0.trigger
OK: 139 MiB in 30 packages
/git-of-theseus # pip install -r requirements.txt
Collecting gitpython (from -r requirements.txt (line 1))
  Using cached GitPython-2.1.3-py2.py3-none-any.whl
Collecting numpy (from -r requirements.txt (line 2))
  Using cached numpy-1.12.1.zip
Collecting progressbar2 (from -r requirements.txt (line 3))
  Using cached progressbar2-3.16.0-py2.py3-none-any.whl
Collecting matplotlib (from -r requirements.txt (line 5))
  Using cached matplotlib-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.0.0]
                    python: yes [2.7.13 (default, Dec 22 2016, 09:22:15)  [GCC
                            6.2.1 20160822]]
                  platform: yes [linux2]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
                       six: yes [six was not found.pip will attempt to install
                            it after matplotlib.]
                  dateutil: yes [dateutil was not found. It is required for date
                            axis support. pip/easy_install may attempt to
                            install it after matplotlib.]
               functools32: yes [functools32 was not found. It is required
                            forPython versions prior to 3.2]
              subprocess32: yes [subprocess32 was not found. It used  for Python
                            versions prior to 3.2 to improves functionality on
                            Linux and OSX]
                      pytz: yes [pytz was not found. pip will attempt to install
                            it after matplotlib.]
                    cycler: yes [cycler was not found. pip will attempt to
                            install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4yzdrE/matplotlib/
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/git-of-theseus # python analyze.py ../shop/
Traceback (most recent call last):
  File "analyze.py", line 18, in <module>
    import argparse, git, datetime, numpy, traceback, time, os, fnmatch, json, progressbar
ImportError: No module named git
/git-of-theseus #
```
