### ISSUE TITLE
AttributeError when running `git-of-theseus-stack-plot authors.json`

### ISSUE THREAD

**Issue by khiav223577** [erikbern/git-of-theseus#42]
I ran `git-of-theseus-analyze .` and got several json files
then ran `git-of-theseus-stack-plot authors.json` and got this error.
How could I fix it?

### authors.json
```json
{"y": [[8, 15, 28, 29, 29, 55, 64, 73, 90, 121, 122, 121, 121], [338, 363, 441, 503, 511, 559, 558, 556, 556, 621, 642, 722, 723]], "labels": ["Rumble Huang", "khiav reoy"], "ts": ["2016-12-29T07:04:30", "2017-01-05T07:33:51", "2017-01-12T17:15:48", "2017-02-07T07:55:19", "2017-02-14T16:28:30", "2017-02-24T03:29:36", "2017-03-11T15:08:56", "2017-04-02T16:15:51", "2017-04-13T07:31:24", "2017-06-21T11:52:27", "2017-07-30T12:27:49", "2017-09-12T12:59:13", "2018-02-12T03:45:04"]}
```
### Error Messages
```
Traceback (most recent call last):
  File "/usr/local/bin/git-of-theseus-stack-plot", line 3, in <module>
    stack_plot()
  File "/Library/Python/2.7/site-packages/git_of_theseus/stack_plot.py", line 60, in stack_plot
    colors=generate_n_colors(len(labels)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 3165, in stackplot
    ret = ax.stackplot(x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 6844, in stackplot
    return mstack.stackplot(self, x, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/stackplot.py", line 101, in stackplot
    **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 7059, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 742, in __init__
    Collection.__init__(self, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py", line 128, in __init__
    self.update(kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 739, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property labels
```

**Comment by erikbern** [comment]
you probably have to update matplotlib. how did you install it?

**Comment by khiav223577** [comment]
Thanks, it works!
But I have no idea how it exists in my computer lol

I got this line when `pip install git-of-theseus`
```
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from git-of-theseus)
```

**Comment by erikbern** [comment]
glad you figured it out!
