### ISSUE TITLE
key errors

### ISSUE THREAD

**Issue by johnscancella** [erikbern/git-of-theseus#6]
Hello I keep seeing errors like these when running
```
Traceback (most recent call last):
  File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: u'58ec10229f8ae648bd978d0aa1e770daa289e89c'
Traceback (most recent call last):
  File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: u'58ec10229f8ae648bd978d0aa1e770daa289e89c'
 99% (454634 of 455317) |################## | Elapsed Time: 0:14:37 ETA: 0:00:01Traceback (most recent call last):
  File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: u'2643750ed2a84571c43ad32278de4a00d24bce46'
Traceback (most recent call last):
  File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: u'2643750ed2a84571c43ad32278de4a00d24bce46'
 99% (455084 of 455317) |################## | Elapsed Time: 0:14:37 ETA: 0:
```
This is being run on https://github.com/LibraryOfCongress/bagit-java

**Comment by erikbern** [comment]
That's weird, I haven't seen that error. Would be great if you can debug a bit and see what's causing it. Seems like it has to do with git commits that come up in `git blame` but don't exist

**Comment by johnscancella** [comment]
seems like it has something to do with what branch it is on. Once I switch to the master branch it works just fine

**Comment by michalmuskala** [comment]
I saw the same error:
```
Traceback (most recent call last):
  File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: u'bc78dd54f3b0b0940a4199ca3dbb5c0ec2861fad'
```

When running the script on https://github.com/elixir-ecto/ecto

**Comment by hawkrives** [comment]
I've got that, running on https://github.com/hawkrives/gobbldygook.

```
File "analyze.py", line 71, in get_file_histogram
    cohort = commit2cohort[old_commit.hexsha]
KeyError: 'bcc9d513a0674c39d5263421851f4ce7372ae77d'
```

I'm going to try cloning a fresh copy and seeing if it still breaks.

**Comment by erikbern** [comment]
great if someone could figure out what's going on
