### ISSUE TITLE
Got InvalidGitRepositoryError when analyze survival.json

### ISSUE THREAD

**Issue by khiav223577** [erikbern/git-of-theseus#72]
Analyze of other json files works well, only `survival.json` raise errors.
```
$ git-of-theseus-analyze survival.json 
Traceback (most recent call last):
  File "/usr/local/bin/git-of-theseus-analyze", line 10, in <module>
    sys.exit(analyze_cmdline())
  File "/usr/local/lib/python2.7/site-packages/git_of_theseus/analyze.py", line 185, in analyze_cmdline
    analyze(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/git_of_theseus/analyze.py", line 30, in analyze
    repo = git.Repo(repo)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 183, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/khiav223577/Desktop/PaGamO2.K/survival.json
```

**Comment by khiav223577** [comment]
I found the problem. I should use `git-of-theseus-stack-plot` to plot.
