### ISSUE TITLE
Got KeyError: 'y' when analyze survival.json

### ISSUE THREAD

**Issue by khiav223577** [erikbern/git-of-theseus#73]
Analyze of other json files works well, only `survival.json` raise errors.

```
$ git-of-theseus-stack-plot survival.json 
Traceback (most recent call last):
  File "/usr/local/bin/git-of-theseus-stack-plot", line 10, in <module>
    sys.exit(stack_plot_cmdline())
  File "/usr/local/lib/python2.7/site-packages/git_of_theseus/stack_plot.py", line 79, in stack_plot_cmdline
    stack_plot(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/git_of_theseus/stack_plot.py", line 37, in stack_plot
    y = numpy.array(data['y'])
KeyError: 'y'
```

**Comment by erikbern** [comment]
yes that file isn't meant to be used with stack plot!
