### ISSUE TITLE
CI/CD integration fails

### ISSUE THREAD

**Issue by ArneBachmannDLR** [erikbern/git-of-theseus#83]
Hi,

I'm having issues using got-analyze from a Gitlab CI/CD job.
The job is set to git clone (not fetch), so I would assume that the entire repository is present...
When it didn't work, I added a command `git checkout main` right before the got command.
Anyway I can't get it running, even tried `--branch %CI_COMMIT_SHA%`:

```
branch 'main' set up to track 'origin/main'.
Switched to a new branch 'main'
Listing all commits                                    : 50 Commits [00:00, 337.65 Commits/s]
Backtracking the master branch                         : 50 Commits [00:00, 614.77 Commits/s]
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\Scripts\git-of-theseus-analyze.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git_of_theseus\analyze.py", line 585, in analyze_cmdline
    analyze(**kwargs)
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git_of_theseus\analyze.py", line 297, in analyze
    if last_date is None or commit.committed_date < last_date - interval:
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\gitdb\util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git\objects\commit.py", line 199, in _set_cache_
    _binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git\db.py", line 48, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(binsha))
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git\cmd.py", line 1269, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git\cmd.py", line 1239, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "C:\ProgramData\mambaforge\envs\test-autocook-3-10\lib\site-packages\git\cmd.py", line 1199, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'2e80fbcd2417ada7a719febe26bb3e8dbae0092a' could not be resolved, git returned: b'2e80fbcd2417ada7a719febe26bb3e8dbae0092a missing'
```

Do you have any hints?

**Comment by erikbern** [comment]
weird, I'm not sure at all what's happening

**Comment by ArneBachmannDLR** [comment]
May be *switched to a **new** branch* is the relevant hint.

**Comment by erikbern** [comment]
Is the issue not happening when you run it locally?

**Comment by ArneBachmannDLR** [comment]
I logged onto the Gitlab runner that runs the job, and invoked the test script, without problems.
New idea: To speed up, Gitlab reduces the lookback depth to default 50, in my case even 10. Since got needs to see the entire history, I suspect that this voluntary reduction makes the analysis impossible. Will try to circumvent this.

**Comment by ArneBachmannDLR** [comment]
Yep, setting the clone depth to 99999 resolved the issue.
The clone depth seems to be backtracking commits to detect merges/splits in the history. If the Gitlab runner only checks out certain commits, got may not be able to analyze the entire history.
